# Generated by Django 3.2 on 2024-03-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
