# Generated by Django 3.2 on 2024-03-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0002_registration_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
